spring:
  data:
    mongodb:
     uri: mongodb+srv://gabriel:gabriel@tsis.wxitp.mongodb.net/gabriel?retryWrites=true&w=majority
     database: ida-database
     #host: database-mongo
     #port: 27017 
     #uri: mongodb://database-mongo/IDA-Users-db
      ##host: 127.0.0.2 #
      ##port: 1111       #
      ##uri: mongodb://127.0.0.2:1111/IDA-Users-db
      #
  application:
    name: MS-Usuarios 

# HTTP Server
server:
  port: 5555   
eureka:
  instance:
    intance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    #service-url.defaultZone: http://eureka-server:8761/eureka
    service-url.defaultZone: http://localhost:8761/eureka
    #service-url.defaultZone: http://192.168.99.100:8761/eureka
  
ribbon: 
  ReadTimeout: 15000

